# --- Prefix & Input ---
set -g prefix C-t
unbind C-b
set -g set-titles off
bind C-t send-prefix
set -sg escape-time 0
set -g mode-keys emacs
set -g status-keys emacs

# --- Copy-Mode Emacs Navigation ---
bind-key -T copy-mode-emacs C-p send-keys -X cursor-up
bind-key -T copy-mode-emacs C-n send-keys -X cursor-down

# --- Clipboard (Mac Terminal.app Workaround) ---
# bind-key -T copy-mode-emacs M-w send-keys -X copy-pipe-and-cancel "pbcopy"
set -s set-clipboard on

# --- Usability & Behavior ---
set -g mouse on
# set -g base-index 1
# setw -g pane-base-index 1
set -g history-limit 10000
set -g display-time 20000

# --- Appearance (Minimal) ---
# 24-Bit TrueColor Support (Goldstandard für moderne Terminals)
set-option -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ",*:RGB"

# Catppuccin Mocha Palette
set -g status-style bg=default,fg="#cdd6f4"
set -g status-left '#[fg="#a6e3a1"][#S] '
set -g window-status-current-style fg="#89b4fa",bold

# Lade lokale Konfiguration, falls vorhanden, ohne Fehlermeldung
source-file -q ~/.tmux.local
