# --- Prefix & Input ---
set -g prefix C-t
unbind C-b
set -g set-titles off
bind C-t send-prefix
set -sg escape-time 0
set -g mode-keys emacs
set -g status-keys emacs

# --- Copy-Mode Emacs Navigation ---
bind-key -T copy-mode-emacs C-p send-keys -X cursor-up
bind-key -T copy-mode-emacs C-n send-keys -X cursor-down

# --- Clipboard (Mac Terminal.app Workaround) ---
bind-key -T copy-mode-emacs M-w send-keys -X copy-pipe-and-cancel "pbcopy"

# --- Usability & Behavior ---
set -g mouse on
# set -g base-index 1
# setw -g pane-base-index 1
set -g history-limit 10000
set -g display-time 20000

# --- Appearance (Minimal) ---
set -g status-style bg=default,fg=white
set -g status-left '#[fg=green][#S] '

# Lade lokale Konfiguration, falls vorhanden, ohne Fehlermeldung
source-file -q ~/.tmux.local
