HISTSIZE=2000
SAVEHIST=2000
HISTFILE=${ZDOTDIR:-$HOME}/.zsh_history

setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt APPEND_HISTORY
setopt SHARE_HISTORY
setopt GLOB_STAR_SHORT
setopt PROMPT_SUBST
setopt INTERACTIVE_COMMENTS

bindkey -e
